### PR TITLE
chore(uses-algoliasearch-beta-10): increases dependency

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request makes the docsearch website use the algoliasearch beta 10. If you see anything out of normal don't hesitate on reporting an issue here: https://github.com/algolia/algoliasearch-client-javascript.

### CODE REVIEW

**Review by francoischalifour — APPROVED** [review]
Good idea to try the new version!

If v4 is SSR-safe, we shouldn't need to dynamically import `algoliasearch`. This was necessary in v3 because of the way the library was packaged.

@nunomaduro Do you want to try to statically import the package to make sure it works in this case?

**Comment by nunomaduro** [comment]
@francoischalifour Done. Can you review it again? By the way, if you know this docsearch-website project well, would be cool if you could try it out quickly.

**Comment by francoischalifour** [comment]
@Shipow @s-pace and I are experimenting with some packages in this repo for now: an upcoming version of Autocomplete.js, an upcoming version of DocSearch.js, Docusaurus 2 alpha and now the Algolia JavaScript client beta.

That's great that it works as a static import now!

**Review by francoischalifour — APPROVED** [review]

**Comment by Shipow** [comment]
thanks @nunomaduro !

**Pull request merged**
